apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: double-minimal-custom-inference
spec:
  predictor:
    containers:
    - name: kserver-container
      image: 'europe-west3-docker.pkg.dev/prokube-internal/prokube-customer/minimal-predictor:latest'
      env:
      - name: MODEL_NAME
        value: "model"
      - name: FACTOR
        value: "2"
      - name: COMPONENT_TYPE
        value: "predictor"
    # in prokube deployments, this can pull the images above
    # adjust to your service account with image pull secret capabilities when pulling from private registry
    serviceAccountName: default-editor
  transformer:
    containers:
    - image: 'europe-west3-docker.pkg.dev/prokube-internal/prokube-customer/minimal-transformer:latest'
      name: kserve-container
      imagePullPolicy: Always
      env:
      - name: POSTGRES_URI
        valueFrom:
          secretKeyRef:
            name: inferencing-postgres-pguser-transformer-admin
            key: uri
      args:
      - --model_name
      - model
    # in prokube deployments, this can pull the images above
    # adjust to your service account with image pull secret capabilities when pulling from private registry
    serviceAccountName: default-editor
