apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: double-minimal-custom-scale-predictor
  namespace: prokube-demo-profile
spec:
  predictor:
    containers:
    - name: scale-predictor-container
      image: 'europe-west3-docker.pkg.dev/prokube-internal/prokube-dev/scale-predictor:latest'
      env:
      - name: MODEL_NAME
        value: "doubler"
      - name: FACTOR
        value: "2"
      - name: COMPONENT_TYPE
        value: "predictor"
    serviceAccountName: default-editor
    imagePullSecrets:
    - name: regcred-prokube-dev
  transformer:
    logger:
      mode: all
    containers:
    - image: 'europe-west3-docker.pkg.dev/prokube-internal/prokube-dev/persistant-transformer:latest'
      name: persist-transformer-container
      env:
      - name: KSERVE_LOGLEVEL
        value: "DEBUG"
      args:
      - --db_url
      - 'postgresql://transformer-admin:g0FRi19npDdfwcDfAZp5l9hf@inferencing-postgres-primary.prokube-demo-profile.svc:5432/scale-inference'
      - --model_name
      - doubler
    imagePullSecrets:
    - name: regcred-prokube-dev
