apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./istio/mirrored-inference-virtual-service.yaml
- ./istio/mirrored-traffic-redirect-virtual-service.yaml
namespace: prokube-demo-profile
