apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: tripler-minimal-custom-scale-predictor
  namespace: prokube-demo-profile
spec:
  predictor:
    containers:
    - name: tripler-predictor-container
      image: 'europe-west3-docker.pkg.dev/prokube-internal/prokube-dev/scale-predictor:latest'
      env:
      - name: MODEL_NAME
        value: "tripler"
      - name: FACTOR
        value: "3"
      - name: COMPONENT_TYPE
        value: "predictor"
    serviceAccountName: default-editor
    imagePullSecrets:
    - name: regcred-prokube-dev
