apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: triple-minimal-custom-scale-predictor
  namespace: prokube-demo-profile
spec:
  predictor:
    containers:
    - name: scale-three-predictor-container
      image: 'europe-west3-docker.pkg.dev/prokube-internal/prokube-dev/scale-predictor:latest'
      env:
      - name: MODEL_NAME
        value: "tripler"
      - name: FACTOR
        value: "3"
      - name: COMPONENT_TYPE
        value: "predictor"
    serviceAccountName: default-editor
    imagePullSecrets:
    - name: regcred-prokube-dev
  transformer:
    containers:
    - image: europe-west3-docker.pkg.dev/prokube-internal/prokube-dev/scale-transformer:latest
      name: persist-transformer-container
      args:
      - --db_url
      - 'postgresql://transformer-admin:g0FRi19npDdfwcDfAZp5l9hf@inferencing-postgres-primary.prokube-demo -profile.svc:5432/scale-inference'
