{
 "title": "Embeddings Inference",
 "description": "These metrics are exposed by containers run using Hugging Face’s Text Embeddings Inference toolkit project (https://github.com/huggingface/text-embeddings-inference).",
 "time": { "from": "now-3h", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "model",
    "label": "Model",
    "query": "embeddings : text-embeddings, reranking : reranking"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(te_request_success{container=\"$model\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(te_request_failure{container=\"$model\"}[$__rate_interval])) by (err)",
     "legendFormat": "Error: {{err}}"
    }
   ]
  },
  {
   "title": "Latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_request_duration_bucket{container=\"$model\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_request_duration_bucket{container=\"$model\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_request_duration_bucket{container=\"$model\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "E2E Latency",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(te_request_duration_bucket{container=\"$model\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Number of replicas",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(te_request_count{container=\"$model\"})",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(te_queue_size{container=\"$model\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 17, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum(te_queue_size{container=\"$model\"})",
     "legendFormat": "Queue size"
    }
   ]
  },
  { "title": "Batching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Input length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_request_input_length_bucket{container=\"$model\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_request_input_length_bucket{container=\"$model\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_request_input_length_bucket{container=\"$model\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Inference quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_request_inference_duration_bucket{container=\"$model\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_request_inference_duration_bucket{container=\"$model\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_request_inference_duration_bucket{container=\"$model\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Queue quantiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(te_request_queue_duration_bucket{container=\"$model\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(te_request_queue_duration_bucket{container=\"$model\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(te_request_queue_duration_bucket{container=\"$model\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}