apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: minimal-custom-transformer
spec:
  predictor:
    containers:
      - name: kserve-container
        # Replace this if you cannot access the prokube.ai registry.
        image: europe-west3-docker.pkg.dev/prokube/development/minimal-custom-kserve-predictor:latest
        env:
        - name: MODEL_NAME
          value: "capitalizer"
        - name: COMPONENT_TYPE
          value: "predictor"
