apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: minimal-custom-transformer
spec:
  predictor:
    containers:
      - name: kserve-container
        image: europe-west3-docker.pkg.dev/prokube-internal/prokube-customer/minimal-custom-kserve-predictor:latest # REPLACE ME if you don't have access to the prokube registry
        env:
        - name: MODEL_NAME
          value: "capitalizer"
        - name: COMPONENT_TYPE
          value: "predictor"
