apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: distilbert-inf-serv
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=distilbert
        - --model_id=distilbert-base-uncased-finetuned-sst-2-english
      resources:
        limits:
          cpu: "4"
          memory: 8Gi
        requests:
          cpu: "2"
          memory: 4Gi
