apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen-inf-serv
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=qwen
        - --model_id=Qwen/Qwen2.5-1.5B-Instruct
        - --enforce-eager
        # - --backend=huggingface  # KServe's huggingface runtime uses vLLM as default when GPU is available
      resources:
        limits:
          cpu: "8"
          memory: 16Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 4Gi
          nvidia.com/gpu: "1"
