apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "v2-mobile-price-classification-inference"
  namespace: "<workspace-name>"
spec:
  predictor:
    serviceAccountName: mlflow-isvc-sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "mlflow://models/mobile-price-svm-<username>/1"
