apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "<inference-name>"
  namespace: "<workspace-name>"
spec:
  predictor:
    serviceAccountName: mlflow-isvc-sa
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "mlflow://models/mobile-price-svm-<your-user>/1"
