[project]
name = "minimal-transformer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.30.0",
    "debugpy>=1.8.15",
    "kserve>=0.15.2",
]
